---

- name: Deploy Portainer to Docker Swarm Cluster
  block:
  - name: Create directory structure
    file: path={{ item }} state=directory mode=755
    with_items:
      - '{{ service_config_path }}'
    tags:
      - init
      - portainer
      - portainer-init

  - name: Configure
    template: src={{ item.src }} dest={{ service_config_path }}/{{ item.dest }} mode={{ item.mode }}
    with_items:
      - { src: docker-compose.yml.j2, dest: docker-compose.yml, mode: 644 }
    notify: docker-update
    tags:
      - conf
      - portainer
      - portainer-conf

  - name: Pull
    shell: docker-compose pull --no-parallel
    register: pullout
    changed_when: "'Downloaded newer image' in pullout.stdout"
    notify: docker-update
    args:
      chdir: '{{ service_config_path }}'
    tags:
      - pull
      - portainer
      - portainer-pull

  - name: Start
    debug:
      msg: Restarting service
    notify: docker-update
    tags:
      - start
      - portainer
      - portainer-start

      
